server:
  port: 8092

spring:
  datasource:
    url: jdbc:h2:./client-service
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /client-service/h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: true

mock-data: true
