server:
  port: 8091

spring:
  datasource:
    url: jdbc:h2:./product-service
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /product-service/h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: true
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

mock-data: true